### ISSUE TITLE
多视图场景生成

### ISSUE THREAD

**Issue by rtzk** [hzxie/CityDreamer#28]
大佬，您的工作太厉害辣！！
请问[CityDreamer](https://github.com/hzxie/CityDreamer)和[[GaussianCity](https://github.com/hzxie/GaussianCity)可以用于从多视图图像中生成场景的mesh，纹理，深度图，法线图等内容吗？

**Comment by hzxie** [comment]
Hi rtzk.

Thanks for your interest in our work!

**Meshes and Textures**

The mesh and textures can be extracted through 3D reconstruction. 
- Please refer to the COLMAP reconstruction results shown in the CityDreamer supplementary material. 
- For GaussianCity, you can also use COLMAP to reconstruct 3D meshes; however, since it is inherently an explicit representation, it can be directly rendered using plugins within Unreal Engine.

**Depth and Normal Maps**

- The depth and normal maps can be extracted from the 3D reconstruction results.
- Because both CityDreamer and GaussianCity rely on voxel ray intersection during computation, the depth and normal maps can also be extracted from this process. Please refer to the code below.

https://github.com/hzxie/CityDreamer/blob/17c218d134a756f0b8c2d4991b5e8bf78f8b4724/scripts/dataset_generator.py#L571-L588

**Comment by rtzk** [comment]
> Hi rtzk.
> 
> Thanks for your interest in our work!
> 
> **Meshes and Textures**
> 
> The mesh and textures can be extracted through 3D reconstruction.
> 
> * Please refer to the COLMAP reconstruction results shown in the CityDreamer supplementary material.
> * For GaussianCity, you can also use COLMAP to reconstruct 3D meshes; however, since it is inherently an explicit representation, it can be directly rendered using plugins within Unreal Engine.
> 
> **Depth and Normal Maps**
> 
> * The depth and normal maps can be extracted from the 3D reconstruction results.
> * Because both CityDreamer and GaussianCity rely on voxel ray intersection during computation, the depth and normal maps can also be extracted from this process. Please refer to the code below.
> 
> https://github.com/hzxie/CityDreamer/blob/17c218d134a756f0b8c2d4991b5e8bf78f8b4724/scripts/dataset_generator.py#L571-L588

好的，谢谢您的回复，我还有另外一个问题，
请问[CityDreamer](https://github.com/hzxie/CityDreamer)和[[GaussianCity](https://github.com/hzxie/GaussianCity)除了直接生成城市布局和 使用来自OpenStreetMap 的光栅化数据外，能否利用带有位姿的图像生成城市布局，例如这些图像来自航拍，但是并不带有实例分割或者高度信息。
如果能直接从带有位姿的多视图图像中直接生成3D场景，我觉得这是令人非常震惊和惊喜的事情！

**Comment by hzxie** [comment]
Hi, rtzk.

I'm not sure I fully understand your question. Are you asking if city layouts can be extracted from the provided images without using instance segmentation or height fields? 

This setting will make 3D reconstruction much simpler, but generating a 3D city is significantly more challenging without semantic or instance data.
